### ISSUE TITLE
it is for wow 335a?

### ISSUE THREAD

**Issue by Helias** [lisacvuk/wow-SRP#1]
it is for wow 335a?

could you add a little installation and usage guide?

**Comment by lisacvuk** [comment]
I tried it on 4.3.4, but it should work for older versions aswell.   
In order to use it, check out https://github.com/lisacvuk/wow-SRP/blob/master/example/main.cpp  

Be aware that this is by no means complete - there is no error checking in place, and this project is very W.I.P.
